# -*- coding: utf-8 -*-
"""SMA_Expt2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrmjcOhoSWs1A1ceErKuqwO9q586AsEW

Extracting comments from youtube video
"""

import requests

video_id = "xTtL8E4LzTQ"

api_key = "AIzaSyDZbWI66nIErg0MwUly3G_yCE06m_C6GNs"

video_info_url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}"
video_info_response = requests.get(video_info_url)
video_info_data = video_info_response.json()

print(video_info_data)

"""Retriev Youtube Videos comments

"""

comments_url = f"https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId={video_id}&key={api_key}"
comments_response = requests.get(comments_url)
comments_data = comments_response.json()

comments_data

#extracting only comments
comments = [item["snippet"]["topLevelComment"]["snippet"]["textDisplay"] for item in comments_data["items"]]
print(comments)

from textblob import TextBlob
def get_comment_sentiment(comment):
  analysis = TextBlob(comment)
  if analysis.sentiment.polarity > 0:
    return "Positive"
  elif analysis.sentiment.polarity == 0:return "Neutral"
  else:
    return "Negative"

# -------- Display the sentiment of YouTube video comments --------
comment_list = []
sentiment_list = []
for comment in comments:
  sentiment = get_comment_sentiment(comment)
  comment_list.append(comment)
  sentiment_list.append(sentiment)
  print(f"{comment} : {sentiment}")

import pandas as pd
sentiment_df = pd.DataFrame({
"Comments": comment_list,
"Sentiment": sentiment_list
})
sentiment_df
sentiment_df.to_csv("YouTube_Comments_Sentiment.csv", index=False)